/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete.interfaz;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import paquete.clase.ActualizarProyecto;
import paquete.clase.CalcularMonto;
import paquete.clase.MostrarProyecto;
import paquete.clase.Proyecto;
import paquete.clase.RegistrarProyecto;

/**
 *
 * @author USER
 */
public class Registro_proyectos extends javax.swing.JFrame {

    public static  Object[] opActualizar= { "ACTUALIZAR", "CANCELAR" };
    /**
     * Creates new form empleado_contacto
     */
    DefaultTableModel modelo;
    JComboBox<String> combo1;
    JComboBox<String> combo2;
    ArrayList<Proyecto> proyecto;
    RegistrarProyecto db = new RegistrarProyecto();
    ActualizarProyecto ac = new ActualizarProyecto();
    MostrarProyecto mp = new MostrarProyecto();
    CalcularMonto cm = new CalcularMonto();
    
    public Registro_proyectos() {
        initComponents();
        //creacion tabla
        modelo = new DefaultTableModel();
        modelo.addColumn("COD PROYECTO");
        modelo.addColumn("NOMBRE PROYECTO");
        modelo.addColumn("RUC");
        modelo.addColumn("ESTADO");
        modelo.addColumn("FECHA INICIO");
        modelo.addColumn("FECHA FIN");
        modelo.addColumn("MONTO");
        modelo.addColumn("PROTOTIPO");
        this.tabla.setModel(modelo);
    }
    
    public void LimpiarFormulario(){
        DefaultTableModel tb = (DefaultTableModel)modelo;
        int i = tb.getRowCount()-1;
        while(i>=0){
            tb.removeRow(i);
            --i;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        codigo_proyecto = new javax.swing.JTextField();
        fecha_inicio = new javax.swing.JTextField();
        nombre_proyecto = new javax.swing.JTextField();
        fecha_fin = new javax.swing.JTextField();
        ruc = new javax.swing.JTextField();
        monto = new javax.swing.JTextField();
        registrar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        buscar_proyecto = new javax.swing.JButton();
        buscar_ruc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        estado = new javax.swing.JComboBox<>();
        prototipo = new javax.swing.JComboBox<>();
        evento = new javax.swing.JButton();
        calc_monto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Registro de Proyectos");
        jLabel1.setToolTipText("");

        jLabel2.setText("Código:");

        jLabel3.setText("Nombre Proyecto:");

        jLabel4.setText("RUC (cliente):");

        jLabel5.setText("Monto:");

        jLabel6.setText("Fecha inicio:");

        jLabel7.setText("Fecha fin:");

        jLabel8.setText("Prototipo:");

        jLabel9.setText("Estado:");

        codigo_proyecto.setToolTipText("");

        nombre_proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_proyectoActionPerformed(evt);
            }
        });

        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        buscar_proyecto.setText("Buscar");
        buscar_proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_proyectoActionPerformed(evt);
            }
        });

        buscar_ruc.setText("Buscar");
        buscar_ruc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_rucActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En ejecucion", "En licitacion", "Entregado", "No se realizo" }));

        prototipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        evento.setText("Ir a Registro de Eventos");
        evento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoActionPerformed(evt);
            }
        });

        calc_monto.setText("Calcular Monto");
        calc_monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc_montoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(codigo_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(146, 146, 146))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombre_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscar_proyecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscar_ruc))
                            .addComponent(calc_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fecha_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(monto, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prototipo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(evento)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(406, 406, 406)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(fecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(monto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(buscar_proyecto)
                    .addComponent(jLabel7)
                    .addComponent(fecha_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar_ruc)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(prototipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calc_monto)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(evento)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_proyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_proyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_proyectoActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // TODO add your handling code here:
        Proyecto p = new Proyecto();
        p.setCodigo_proyecto(codigo_proyecto.getText());
        p.setNombre_proyecto(nombre_proyecto.getText());
        p.setRUC(ruc.getText());
        String e = estado.getSelectedItem().toString();
        p.setEstado(e);
        p.setFecha_inicio(fecha_inicio.getText());
        p.setFecha_fin(fecha_fin.getText());
        p.setMonto(Integer.parseInt(monto.getText()));
        String proto = prototipo.getSelectedItem().toString();
        p.setPrototipo(proto);
        if(!"".equals(codigo_proyecto.getText()))
        {
            db.registrarProyecto(p);
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Falta ingresar datos");
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void eventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoActionPerformed
        // TODO add your handling code here:
        Registro_eventos abrir = new Registro_eventos();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_eventoActionPerformed

    private void buscar_proyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_proyectoActionPerformed
        // TODO add your handling code here:
        LimpiarFormulario();
        proyecto = mp.ListProyectoNombre(nombre_proyecto.getText());
        for(Proyecto p: proyecto)
        {
            modelo.addRow(new Object[]{p.getCodigo_proyecto(),p.getNombre_proyecto(),p.getRUC(),p.getEstado(),p.getFecha_inicio(),p.getFecha_fin(),p.getMonto(),p.getPrototipo()});
        }
    }//GEN-LAST:event_buscar_proyectoActionPerformed

    private void buscar_rucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_rucActionPerformed
        // TODO add your handling code here:
        LimpiarFormulario();
        proyecto = mp.ListProyectoRUC(ruc.getText());
        for(Proyecto p: proyecto)
        {
            modelo.addRow(new Object[]{p.getCodigo_proyecto(),p.getNombre_proyecto(),p.getRUC(),p.getEstado(),p.getFecha_inicio(),p.getFecha_fin(),p.getMonto(),p.getPrototipo()});
        }
    }//GEN-LAST:event_buscar_rucActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        Proyecto p = new Proyecto();
        p.setCodigo_proyecto(codigo_proyecto.getText());
        p.setNombre_proyecto(nombre_proyecto.getText());
        p.setRUC(ruc.getText());
        String e = estado.getSelectedItem().toString();
        p.setEstado(e);
        p.setFecha_inicio(fecha_inicio.getText());
        p.setFecha_fin(fecha_fin.getText());
        p.setMonto(Integer.parseInt(monto.getText()));
        String proto = prototipo.getSelectedItem().toString();
        p.setPrototipo(proto);
        if(!"".equals(codigo_proyecto.getText()))
        {
            int Acction = JOptionPane.showOptionDialog(this, "Esta seguro de actualizar los datos? ", "Mensaje", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opActualizar, opActualizar[0]);
            if (Acction == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "Datos Actualizados ");
                ac.UpdateProyecto(p);
            } else {
                JOptionPane.showMessageDialog(this, "Se cancelo la operacion","Mensaje",JOptionPane.CANCEL_OPTION);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Busca datos en la DB primero","Mensaje",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void calc_montoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_montoActionPerformed
        // TODO add your handling code here:
        int monto_total = cm.CalcularMonto(ruc.getText());
        JOptionPane.showMessageDialog(rootPane, "El monto total para este cliente es: " + monto_total);
    }//GEN-LAST:event_calc_montoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro_proyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro_proyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro_proyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro_proyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_proyectos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton buscar_proyecto;
    private javax.swing.JButton buscar_ruc;
    private javax.swing.JButton calc_monto;
    private javax.swing.JTextField codigo_proyecto;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JButton evento;
    private javax.swing.JTextField fecha_fin;
    private javax.swing.JTextField fecha_inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField monto;
    private javax.swing.JTextField nombre_proyecto;
    private javax.swing.JComboBox<String> prototipo;
    private javax.swing.JButton registrar;
    private javax.swing.JTextField ruc;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
