CREATE OR REPLACE FUNCTION CALCULAR_MONTO_TOTAL(RUC_C PROYECTO.RUC%TYPE) 
RETURN NUMBER AS
    MONTO_TOTAL NUMBER;
BEGIN
    SELECT SUM(P.MONTO)
    INTO monto_total
    FROM PROYECTO P, CLIENTE C
    WHERE P.RUC = C.RUC
    AND C.RUC = RUC_C;
    
    RETURN MONTO_TOTAL;
END;