DROP TABLE EVENTO;
DROP TABLE PROYECTO;
DROP TABLE CLIENTE;
DROP TABLE CORREO_CONTACTO;
DROP TABLE TELEFONO_CONTACTO;
DROP TABLE CONTRATO;
DROP TABLE CONTACTO;

SELECT * FROM PROYECTO;
SELECT * FROM EVENTO;

SELECT P.CODIGO_PROYECTO, P.NOMBRE_PROYECTO, C.RUC, P.ESTADO, P.FECHA_INICIO, P.FECHA_FIN, P.MONTO, P.PROTOTIPO
FROM PROYECTO P, CLIENTE C
WHERE P.RUC = C.RUC
AND P.NOMBRE_PROYECTO = 'Software Factory Desarrollo y Soporte';

SELECT P.CODIGO_PROYECTO, P.NOMBRE_PROYECTO, C.RUC, P.ESTADO, P.FECHA_INICIO, P.FECHA_FIN, P.MONTO, P.PROTOTIPO
FROM PROYECTO P, CLIENTE C
WHERE P.RUC = C.RUC
AND C.RUC = '20142829551';

SELECT E.CODIGO_EVENTO, P.CODIGO_PROYECTO, P.NOMBRE_PROYECTO, C.RUC, C.NOMBRE_EMPRESA, E.FECHA, E.DESCRIPCION
FROM EVENTO E, CLIENTE C, PROYECTO P
WHERE E.CODIGO_PROYECTO = P.CODIGO_PROYECTO
AND P.RUC = C.RUC
AND C.RUC = '20101036813';

SELECT E.CODIGO_EVENTO, P.CODIGO_PROYECTO, P.NOMBRE_PROYECTO, C.RUC, C.NOMBRE_EMPRESA, E.FECHA, E.DESCRIPCION
FROM EVENTO E, CLIENTE C, PROYECTO P
WHERE E.CODIGO_PROYECTO = P.CODIGO_PROYECTO
AND P.RUC = C.RUC
AND P.CODIGO_PROYECTO = '1005';

SET SERVEROUTPUT ON

DECLARE
    MONTO NUMBER;
BEGIN
    MONTO := CALCULAR_MONTO_TOTAL(20101036813);
    DBMS_OUTPUT.PUT_LINE('EL MONTO TOTAL ES: ' || MONTO);
END;